import logging
import os
from typing import Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

logger = logging.getLogger(__name__)


class PDFService:
    """Generate PDF comic books from panels with images and text."""

    def __init__(self, output_dir: str = "./output"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_comic_pdf(
        self,
        title: str,
        panels: list[dict],
        output_filename: Optional[str] = None,
    ) -> str:
        """
        Generate a PDF with comic panels.
        Each panel gets its own page with image + description + dialogue.

        panels: list of dicts with keys:
            - panel_number: int
            - description: str
            - dialogue: str | None
            - image_path: str | None
        """
        if not output_filename:
            safe_title = "".join(c if c.isalnum() or c in " _-" else "" for c in title)
            output_filename = f"{safe_title.strip()}.pdf"

        pdf_path = os.path.join(self.output_dir, output_filename)
        page_width, page_height = A4

        c = canvas.Canvas(pdf_path, pagesize=A4)

        # ─── Title page ───────────────────────────────────────────────────────
        c.setFont("Helvetica-Bold", 28)
        c.drawCentredString(page_width / 2, page_height - 6 * cm, title)

        c.setFont("Helvetica", 14)
        c.drawCentredString(page_width / 2, page_height - 8 * cm, f"{len(panels)} panels")
        c.drawCentredString(page_width / 2, page_height - 9 * cm, "Generated by Comic AI")

        c.showPage()

        # ─── Panel pages ──────────────────────────────────────────────────────
        for panel in panels:
            panel_num = panel.get("panel_number", 0)
            description = panel.get("description", "")
            dialogue = panel.get("dialogue", "")
            image_path = panel.get("image_path")

            # Panel header
            c.setFont("Helvetica-Bold", 16)
            c.drawString(2 * cm, page_height - 2 * cm, f"Panel {panel_num}")

            # Image
            img_y = page_height - 3 * cm  # top of image area
            if image_path and os.path.exists(image_path):
                try:
                    img = ImageReader(image_path)
                    img_width = 14 * cm
                    img_height = 14 * cm
                    img_x = (page_width - img_width) / 2
                    img_y = page_height - 3 * cm - img_height

                    c.drawImage(
                        img,
                        img_x, img_y,
                        width=img_width, height=img_height,
                        preserveAspectRatio=True,
                        anchor="n",
                    )
                except Exception as e:
                    logger.error("Failed to load image for panel %d: %s", panel_num, e)
                    c.setFont("Helvetica-Oblique", 12)
                    c.drawString(2 * cm, page_height - 10 * cm, f"[Image failed to load: {image_path}]")
                    img_y = page_height - 11 * cm
            else:
                c.setFont("Helvetica-Oblique", 12)
                c.drawString(2 * cm, page_height - 5 * cm, "[No image generated]")
                img_y = page_height - 6 * cm

            # Description text
            text_y = img_y - 1.5 * cm
            c.setFont("Helvetica", 11)
            # Wrap text manually
            text_lines = self._wrap_text(description, max_chars=80)
            for line in text_lines:
                if text_y < 3 * cm:
                    break
                c.drawString(2 * cm, text_y, line)
                text_y -= 0.5 * cm

            # Dialogue (if any)
            if dialogue:
                text_y -= 0.5 * cm
                c.setFont("Helvetica-Bold", 11)
                dialogue_lines = self._wrap_text(f'"{dialogue}"', max_chars=75)
                for line in dialogue_lines:
                    if text_y < 2 * cm:
                        break
                    c.drawString(2.5 * cm, text_y, line)
                    text_y -= 0.5 * cm

            c.showPage()

        c.save()
        logger.info("PDF generated: %s", pdf_path)
        return pdf_path

    def _wrap_text(self, text: str, max_chars: int = 80) -> list[str]:
        """Simple text wrapping by character count."""
        words = text.split()
        lines = []
        current_line = ""

        for word in words:
            if len(current_line) + len(word) + 1 <= max_chars:
                current_line += (" " if current_line else "") + word
            else:
                if current_line:
                    lines.append(current_line)
                current_line = word

        if current_line:
            lines.append(current_line)

        return lines
